### PR TITLE
Warn when package summary end with period

### PR DESCRIPTION
**Pull request by conao3**
Hi!

Proposal that summary should not end with period.
Currently, almost packages' summary doesn't end with period but some packages not.

### CODE REVIEW

**Comment by purcell** [comment]
Makes sense, thanks! Would you mind changing "should not end with period" to "should not end with a period" please?

**Comment by conao3** [comment]
OK!

**Comment by purcell** [comment]
Great, thank you!

**Comment by conao3** [comment]
Thanks!

**Pull request merged**
