### PR TITLE
[WIP] Initial support for multi-file packages

### PR DESCRIPTION
**Pull request by purcell**
See #111.

This initial support allows `package-lint` to be run on secondary files in multi-file packages, provided that the new variable `package-buffer-main-file` is set to point at the main `.el` or `-pkg.el` file. The package name and its dependencies are then obtained from that main file instead of the current file.

Needs more tests, which I will add in due course (unless anybody else wants to). I might merge this relatively soon and try it out in some real-world multi-file projects.

Over time I would hope that some auto-detection of main files would be possible, e.g. if there's a `-pkg.el` neighbour for the current file.

Happy to get feedback.

### CODE REVIEW

**Comment by riscy** [comment]
This looks awesome!

**Comment by purcell** [comment]
> This looks awesome!

Even with the variable, I think that for `melpazoid` purposes you could easily determine the "main" file: it would be the first that exists out of `recipename-pkg.el` or `recipename.el`. Though of course the `:files` spec might make this difficult. Probably you'd try building the package first, then look at its contents: if a `tar` file, you'd do the above.

**Comment by purcell** [comment]
Merged this for now, and I'll test CI integration in a different multi-file repo, like `elm-mode`, `haskell-mode` or `ledger-mode`... Once confirmed working, I'll write up the docs, tidy up the code and ensure some test coverage.

**Comment by purcell** [comment]
(This is where it's handy for me to be able to force the immediate rebuild of a MELPA package...)

**Comment by purcell** [comment]
Seems to be working for `elm-mode`, at least.

**Comment by purcell** [comment]
Notable limitation is that it doesn't handle linting `-pkg.el` files yet.

**Comment by DamienCassou** [comment]
I get

> Error from syntax checker emacs-lisp-package: Wrong type argument: stringp, nil

when flycheck runs in mpdel.el in the branch of this PR: https://gitea.petton.fr/mpdel/mpdel/pulls/27. I haven't investigated more.

**Comment by purcell** [comment]
Cool, if you have a traceback, file an issue and I'll get to it soon. :-)

**Comment by alphapapa** [comment]
@DamienCassou Not sure if it will help, but see https://github.com/alphapapa/makem.sh/commit/ba3a78f61de6fccc59d06f8389df83745c946b02.  It seems to work on `org-ql`.

@purcell Thanks, this makes package-lint's output *much* more useful on multi-file packages!

**Comment by purcell** [comment]
> when flycheck runs in mpdel.el in the branch of this PR: https://gitea.petton.fr/mpdel/mpdel/pulls/27. I haven't investigated more.

I tried but couldn't reproduce this, btw. :-/

**Comment by DamienCassou** [comment]
Steve Purcell <notifications@github.com> writes:
> Cool, if you have a traceback, file an issue and I'll get to it soon. :-)

do you know a way to debug a flycheck checker?

I'm on Emacs 27 by the way.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by purcell** [comment]
> do you know a way to debug a flycheck checker?

Well, first I'd try calling `package-lint-buffer` directly, since the flycheck checker is a thin wrapper.

> I'm on Emacs 27 by the way.

26.3 here.

**Pull request merged**
