### PR TITLE
Test for reserved keybindings

### PR DESCRIPTION
**Pull request by alphapapa**
cf. #79

### CODE REVIEW

**Comment by Fanael** [comment]
> FIXME: This also catches "C-c C-x", which is allowable, but I don't know how to get the modifier of the C-x.

Call `event-modifier` on `(aref lks 1)`.

**Comment by alphapapa** [comment]
Thanks, it seems to be working now.

**Comment by purcell** [comment]
Cool! It's not clear to me why the build is still failing, though?

**Comment by alphapapa** [comment]
> Cool! It's not clear to me why the build is still failing, though?

Me neither.  The tests all pass when I run `ert-run-tests-interactively`.  And some of the other commits I pushed like this passed the tests, except on Emacs 24.1 and 24.2.

**Comment by purcell** [comment]
I tracked down the problem. Bear with me.

**Comment by purcell** [comment]
The code wasn't really doing the right thing when there was a `(kbd "...")` inside a `(define-key` or similar. I've simplified it and made it a bit more robust, and also changed the message so that it is the same for all cases, and simply refers people to the corresponding manual section.

**Comment by alphapapa** [comment]
Thanks.

**Comment by alphapapa** [comment]
Thanks.  I made so many mistakes in this code that I'm not sure it saved you any time over writing it yourself.

**Comment by purcell** [comment]
> Thanks. I made so many mistakes in this code that I'm not sure it saved you any time over writing it yourself.

LOL, that's not true - I wouldn't have got round to writing it without you starting the ball rolling.

**Pull request merged**
