### PR TITLE
"Homepage" is a valid url header keywords 

### PR DESCRIPTION
**Pull request by tarsius**
Please see the commit messages.

### CODE REVIEW

**Comment by joewreschnig** [comment]
I don't mind "Homepage" but I don't think we should permit "X-..." headers, if the point of package-lint is to enforce best practices.

**Comment by tarsius** [comment]
Yeah, I did that in a separate commit for easy dropability.

**Comment by tarsius** [comment]
Ah, and it seems I have to update the tests. Will do that after @purcell has decided what to do about `X-*`.

**Comment by purcell** [comment]
Yeah, I think I agree with @joewreschnig here that we should disallow `X-*`. If @tarsius has stats indicating that `X-URL` is a de-facto standard, I'm happy to let that slide though.

**Comment by tarsius** [comment]
No stats this time. And I would prefer if maintainers dropped the unnecessary `X-` too.

**Comment by Fanael** [comment]
I agree that we should recognize `Homepage`, but I'm going to reject this PR because the check should be rewritten to simply use `lm-homepage` instead.

**Comment by Fanael** [comment]
Whoops, `lm-homepage` is not defined in Emacs 24.3 and below.

**Comment by Fanael** [comment]
> I don't mind "Homepage" but I don't think we should permit "X-..." headers, if the point of package-lint is to enforce best practices.

Thirded.

> Ah, and it seems I have to update the tests.

Yeah, if you do that it'll be ready to merge.

**Comment by Fanael** [comment]
Actually, don't bother, I'll do it: rebased and amended as ff64e1171e8.

**Comment by purcell** [comment]
Thanks all!

**Comment by tarsius** [comment]
Thanks!

**Pull request closed without merging**
