### PR TITLE
Suppress the error on ol.el if org 9.3 is installed

### LINKED ISSUE #195: ol.el (org-link-*) compatibility issue
Hi, I'm currently trying to vanish linting errors from my [org-multi-wiki](https://github.com/akirak/org-multi-wiki) package.

This package adds a custom link type to Org. Since Org 9.3, `ol.el` has been added, and `org-make-link-string` was renamed to `org-link-make-string`. It is shipped with Emacs 27.1.

My package specifies Org 9.3 and Emacs 26.1 as its dependencies in the `Package-Requires` header, and I receive the following errors from `package-lint`:

> org-multi-wiki.el:46:16: error: You should depend on (emacs "27.1") if you need `ol'.
> 
> org-multi-wiki.el:47:53: error: You should depend on (emacs "27.1") if you need `org-link-make-string'.

I want to avoid dependency on Emacs 27.1 wherever possible, because some major distributions don't have it yet. Having Org 9.3 should be sufficient.

Is it possible to fix this issue, or is there a workaround?

### PR DESCRIPTION
**Pull request by akirak**
Fixes #195.

Following the advice by @purcell, I've added an optional field to `package-lint-backport-libraries` to allow specifying the backport package containing the feature.

The code has become slightly more complicated, so you can tidy up the function. Also `package-lint-backport-libraries` may not be of the best quality, so please feel free to improve it.

### CODE REVIEW

**Comment by akirak** [comment]
The stdlib-changes action has failed. What should I do?

**Comment by purcell** [comment]
> The stdlib-changes action has failed. What should I do?

That one's a bit flaky, please disregard for now.

**Comment by akirak** [comment]
I ran it locally, and `(require 'ol)` produces an error if and only if none of `(emacs 27.1)` and `(org 9.3)` is included in the dependencies. I think this PR is ready for merging.

**Comment by purcell** [comment]
> I think this PR is ready for merging.

Yeah, I was hoping to refactor the data structure a little first, but that can be done later. Thanks!

**Comment by akirak** [comment]
I see, thanks!

**Pull request merged**
