### PR TITLE
Warn about requiring cl-lib <=0.5 on Emacs >=24.3

### PR DESCRIPTION
**Pull request by lassik**
Ping @riscy

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, I think this makes sense... would you be able to add a test case please?

**Comment by purcell** [comment]
Awesome, thank you!

**Comment by lassik** [comment]
Is 0.5 the right cl-lib version btw?

**Comment by purcell** [comment]
Good question... it's probably `< 1.0` we need to worry about, actually. The version included in Emacs 24.3 is 1.0.

**Comment by purcell** [comment]
^ I've tweaked this accordingly in 8edc96b

**Comment by purcell** [comment]
Interestingly, the cl-lib version bundled in Emacs is always 1.0, so even if `cl-lib 0.7` has additions relative to the `cl-lib 1.0` bundled in Emacs 24.3, there's no way to declare a dependency on it.

**Comment by lassik** [comment]
Since `cl-lib 1.0` satisfies all dependency declarations of the form `cl-lib 0.x`, isn't it impossible to meaningfully declare a dependency on `cl-lib` in Emacs >= 24.3?

**Comment by conao3** [comment]
On the other hand, all packages should enable `lexical-binding`. [ref comment](https://github.com/cask/cask/issues/480#issuecomment-641140359).

This requirement requires a modern package (and that it work with most Emacs packages), it is reasonable to set Emacs-24.4 as the minimum requirement for Emacs is.
From this requirement, it may be possible to simplify the check, I think.

**Comment by lassik** [comment]
Wasn't the `lexical-binding` declaration introduced in Emacs 24.1?

**Comment by purcell** [comment]
> Since `cl-lib 1.0` satisfies all dependency declarations of the form `cl-lib 0.x`, isn't it impossible to meaningfully declare a dependency on `cl-lib` in Emacs >= 24.3?

Yes, but I guess I'm allowing for a world in which ELPA might eventually get cl-lib 1.x.  Or perhaps I'm misunderstanding your question?

**Comment by lassik** [comment]
However, since cl-lib was added in 24.4, perhaps 24.4 would be a useful minimum version. In practice, it's probably not possible to use a large number of MELPA packages (i.e. a large number of the useful Emacs packages that exist anywhere) without cl-lib.

**Comment by purcell** [comment]
`cl-lib` was added in 24.3.

**Comment by lassik** [comment]
You can install cl-lib on Emacs <24.4, but it might be easier just to upgrade :) 24.4 was released almost six years ago.

**Comment by lassik** [comment]
Ah, right :D Well, that's more than 7 years ago.

**Comment by lassik** [comment]
https://www.gnu.org/software/emacs/history.html

**Comment by purcell** [comment]
> You can install cl-lib on Emacs <24.4, but it might be easier just to upgrade :) 24.4 was released almost six years ago.

Yes, true, but `package-lint` isn't here to tell people when to start using newer versions, just to help them understand what technically works. In practice, I've written a couple of packages that are fine with just `(emacs "24.1") (cl-lib "0.5")` deps.

**Comment by conao3** [comment]
I miss memorizing the dependency...
Sorry for the noise. After all, the machine should do these checks :)

**Comment by lassik** [comment]
> > Since `cl-lib 1.0` satisfies all dependency declarations of the form `cl-lib 0.x`, isn't it impossible to meaningfully declare a dependency on `cl-lib` in Emacs >= 24.3?
> 
> Yes, but I guess I'm allowing for a world in which ELPA might eventually get cl-lib 1.x. Or perhaps I'm misunderstanding your question?

If you mean manually specifying cl-lib >= 1.1 in the deps, that makes sense.

Would it be logical for package-lint to warn whenever cl-lib <= 1.0 is mentioned in deps?

**Comment by lassik** [comment]
Slightly off-topic, but Repology is an awesome site for checking out which distros ship with what Emacs version btw: https://repology.org/project/emacs/versions

**Pull request merged**
